In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.2'

# Creating Arrays from Scratch

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3,5),3.1415)

array([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.random.random((3,3))

array([[0.44027149, 0.83565431, 0.26354165],
       [0.49217737, 0.27187504, 0.93780927],
       [0.62061186, 0.09245125, 0.49370377]])

In [10]:
np.random.normal(0,1,(3,3))

array([[ 1.05676845,  1.201535  ,  0.08455931],
       [ 1.90993282, -1.02839577, -0.63684618],
       [ 0.95545636, -0.37445091, -0.31645261]])

In [11]:
np.random.randint(0,10,(3,3))

array([[6, 6, 8],
       [4, 0, 1],
       [4, 9, 1]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])

## Numpy standard data types

In [14]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [15]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Data type   Description
- bool_ ->           Boolean (True or False) stored as a byte
- int_    ->        Default integer type (same as C long ; normally either - int64 or int32 )
- intc      ->      Identical to C int (normally int32 or int64 )
- intp        ->    Integer used for indexing (same as C ssize_t ; normally - either int32 or int64 )
- int8          ->  Byte (–128 to 127)
- int16->           Integer (–32768 to 32767)
- int32  ->         Integer (–2147483648 to 2147483647)
- int64    ->       Integer (–9223372036854775808 to 9223372036854775807)
- uint8      ->     Unsigned integer (0 to 255)
- uint16       ->   Unsigned integer (0 to 65535)
- uint32         -> Unsigned integer (0 to 4294967295)
- uint64->          Unsigned integer (0 to 18446744073709551615)
- float_  ->        Shorthand for float64
- float16   ->      Half-precision float: sign bit, 5 bits exponent, 10 bits - mantissa
- float32      ->   Single-precision float: sign bit, 8 bits exponent, 23 - - - bits mantissa
- float64        -> Double-precision float: sign bit, 11 bits exponent, 52 - - bits mantissa
- complex_ ->       Shorthand for complex128
- complex64  ->     Complex number, represented by two 32-bit floats
- complex128   ->   Complex number, represented by two 64-bit floats

In [16]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [17]:
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [19]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [21]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
