In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.2'

# Creating Arrays from Scratch

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5),3.1415)

array([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.random.random((3,3))

array([[0.50531822, 0.17599162, 0.23300023],
       [0.18995862, 0.78389368, 0.77085182],
       [0.29087544, 0.92707386, 0.00202896]])

In [9]:
np.random.normal(0,1,(3,3))

array([[ 1.08774212,  0.53339549, -0.01583934],
       [-0.67275143, -1.35343324,  0.35617931],
       [-0.87081201,  0.5323852 ,  0.32042066]])

In [10]:
np.random.randint(0,10,(3,3))

array([[8, 8, 4],
       [9, 3, 8],
       [0, 1, 5]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty(3)

array([1., 1., 1.])

## Numpy standard data types

In [13]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [14]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Data type   Description
- bool_ ->           Boolean (True or False) stored as a byte
- int_    ->        Default integer type (same as C long ; normally either - int64 or int32 )
- intc      ->      Identical to C int (normally int32 or int64 )
- intp        ->    Integer used for indexing (same as C ssize_t ; normally - either int32 or int64 )
- int8          ->  Byte (–128 to 127)
- int16->           Integer (–32768 to 32767)
- int32  ->         Integer (–2147483648 to 2147483647)
- int64    ->       Integer (–9223372036854775808 to 9223372036854775807)
- uint8      ->     Unsigned integer (0 to 255)
- uint16       ->   Unsigned integer (0 to 65535)
- uint32         -> Unsigned integer (0 to 4294967295)
- uint64->          Unsigned integer (0 to 18446744073709551615)
- float_  ->        Shorthand for float64
- float16   ->      Half-precision float: sign bit, 5 bits exponent, 10 bits - mantissa
- float32      ->   Single-precision float: sign bit, 8 bits exponent, 23 - - - bits mantissa
- float64        -> Double-precision float: sign bit, 11 bits exponent, 52 - - bits mantissa
- complex_ ->       Shorthand for complex128
- complex64  ->     Complex number, represented by two 32-bit floats
- complex128   ->   Complex number, represented by two 64-bit floats

In [15]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [20]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [26]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [28]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [32]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [33]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [34]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Splitting NumPy Arrays

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [46]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Arrays


In [50]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)


(array([0, 2, 4, 6]),)


In [53]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [54]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [55]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sorting Arrays


In [56]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [57]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [58]:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [59]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays

In [60]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [61]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [62]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [63]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Random Numbers in NumPy

In [66]:
from numpy import random
x = random.randint(100)

print(x)

5


In [67]:
x = random.rand()

print(x)

0.2384169847175236


In [68]:
x=random.randint(100, size=(5))

print(x)

[77 64 80 65 99]


In [69]:
x = random.randint(100, size=(3, 5))

print(x)

[[41 18 65 78 14]
 [56  5 37 75 60]
 [56 66 52 22 92]]


In [70]:
x = random.rand(5)

print(x)

[0.00084686 0.20786255 0.23393196 0.58226235 0.50013923]


In [71]:
x = random.rand(3, 5)

print(x)

[[0.89593171 0.79649121 0.42039169 0.55126269 0.56376772]
 [0.37284477 0.46870687 0.26342009 0.7307191  0.26887037]
 [0.71282393 0.09253886 0.58846393 0.12594757 0.668938  ]]


In [72]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [73]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 7 9 9 5]
 [3 9 5 9 5]
 [3 3 9 9 5]]


## Random Data Distribution

### What is Data Distribution?
    Data Distribution is a list of all possible values, and how often each value occurs.

    Such lists are important when working with statistics and data science.

    The random module offer methods that returns randomly generated data distributions.

### Random Distribution
    A random distribution is a set of random numbers that follow a certain probability density function.

    **Probability Density Function**: A function that describes a continuous probability. i.e. probability of all values in an array.

    We can generate random numbers based on defined probabilities using the choice() method of the random module.

    The choice() method allows us to specify the probability for each value.

    The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

### Example
    Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

    The probability for the value to be 3 is set to be 0.1

    The probability for the value to be 5 is set to be 0.3

    The probability for the value to be 7 is set to be 0.6

    The probability for the value to be 9 is set to be 0

In [74]:

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 5 7 5 5 7 7 7 5 7 5 5 7 7 5 7 3 7 7 7 5 7 7 7 7 7 7 5 5 7 7 5 7 7 7
 3 5 5 7 7 5 7 7 7 7 7 7 7 7 7 5 7 5 3 7 7 7 7 5 7 7 7 7 7 5 7 3 7 5 7 7 5
 5 5 3 7 7 5 5 5 5 7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 5 5]


In [75]:

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 5 5 7 5]
 [3 5 7 3 7]
 [7 7 7 7 3]]


## Random Permutations

In [76]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 3 4 2 1]


In [77]:

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 2 1 4 5]
