In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.2'

# Creating Arrays from Scratch

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5),3.1415)

array([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.random.random((3,3))

array([[0.65111326, 0.36772058, 0.05960085],
       [0.87989216, 0.83519153, 0.09451441],
       [0.16690115, 0.32980724, 0.61163331]])

In [9]:
np.random.normal(0,1,(3,3))

array([[-1.61209473,  0.41497664, -0.51486581],
       [ 1.29447164, -1.44835562, -0.18322434],
       [ 0.92964692, -0.14446323,  0.35284961]])

In [10]:
np.random.randint(0,10,(3,3))

array([[9, 0, 8],
       [1, 1, 8],
       [4, 5, 6]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty(3)

array([1., 1., 1.])